import {
  IconSun,
  IconMoon,
  IconMenu2,
  IconX,
  IconAlertTriangle,
  IconCalendar,
  IconRefresh,
  IconBuilding,
  IconCheck,
  IconMapPin,
  IconMicrophone,
  IconAward,
  IconUsers,
  IconBookmark,
  IconLanguage,
  IconChevronLeft,
  IconChevronRight,
  IconArrowRight,
  IconHeadset,
  IconShield,
  IconFile,
  IconMail,
  IconClock,
  IconWorld,
  IconArrowUp,
  IconBrandGithub,
  IconBrandLinkedin,
  IconBrandFacebook,
  // New icons for full FA migration
  IconMap,
  IconTrophy,
  IconBrandApple,
  IconBrandGooglePlay,
  IconBell,
  IconBook,
  IconSettings,
  IconServer,
  IconNetwork,
  IconBrandWordpress,
  IconHome,
  IconEdit,
} from "@tabler/icons-react";

export const Icons = {
  Sun: IconSun,
  Moon: IconMoon,
  Menu: IconMenu2,
  Close: IconX,
  Alert: IconAlertTriangle,
  Calendar: IconCalendar,
  Refresh: IconRefresh,
  Building: IconBuilding,
  Check: IconCheck,
  MapPin: IconMapPin,
  Microphone: IconMicrophone,
  Award: IconAward,
  Users: IconUsers,
  Bookmark: IconBookmark,
  Language: IconLanguage,
  ChevronLeft: IconChevronLeft,
  ChevronRight: IconChevronRight,
  ArrowRight: IconArrowRight,
  Headset: IconHeadset,
  Shield: IconShield,
  File: IconFile,
  Mail: IconMail,
  Clock: IconClock,
  Globe: IconWorld,
  ArrowUp: IconArrowUp,
  Github: IconBrandGithub,
  LinkedIn: IconBrandLinkedin,
  Facebook: IconBrandFacebook,
  // New aliases
  Map: IconMap,
  Trophy: IconTrophy,
  Apple: IconBrandApple,
  GooglePlay: IconBrandGooglePlay,
  Bell: IconBell,
  Book: IconBook,
  Settings: IconSettings,
  Server: IconServer,
  Network: IconNetwork,
  WordPress: IconBrandWordpress,
  Home: IconHome,
  Edit: IconEdit,
};
